server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:spring.p12
    key-alias: spring
    key-store-password: password
  servlet:
    context-path: /
  port: 8443

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 297865767597-qclbnrj2kl2r8kod2tse20n5l2jbp0a6.apps.googleusercontent.com
            client-secret: ${OAUTH2_CLIENT_SECRET}
          github:
            client-id: f3edb75f044cb225bc85
            client-secret: ${OAUTH2_GITHUB_CLIENT_SECRET}
          facebook:
            client-id: 1684224615419514
            client-secret: ${OAUTH2_FACEBOOK_CLIENT_SECRET}

logging:
  level:
    org:
      springframework:
        boot:
          actuate: DEBUG
        security: DEBUG
