spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 297865767597-qclbnrj2kl2r8kod2tse20n5l2jbp0a6.apps.googleusercontent.com
            client-secret: ${OAUTH2_CLIENT_SECRET}

logging:
  level:
    org:
      springframework:
        security: DEBUG
